name: CI

on: [push, pull_request]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    env:
      CI_BUILD_WHEEL: 1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install tox
      - run: tox -e cibuild -- build
      - uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: release/dist
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        # Old Ubuntu version for old glibc
        os: [macos-10.15, windows-2019, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    env:
      CI_BUILD_PYINSTALLER: 1
      CI_BUILD_WININSTALLER: ${{ matrix.os == 'windows-2019' }}
      CI_BUILD_KEY: ${{ secrets.CI_BUILD_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - if: matrix.os == 'windows-latest'
        uses: actions/cache@v1
        with:
          path: release/installbuilder/setup
          key: installbuilder
      - run: pip install tox
      - run: tox -e cibuild -- build
      # artifacts must have different names, see https://github.com/actions/upload-artifact/issues/24
      - uses: actions/upload-artifact@v2
        with:
          name: binaries.${{ matrix.os }}
          path: release/dist

  # Separate from everything else because slow.
  build-and-deploy-docker:
    if: github.repository == 'recipopdev/mitmproxy' && github.event_name == 'push'
    needs: [test, test-web-ui, build-wheel]
    runs-on: ubuntu-latest
    env:
      CI_BUILD_DOCKER: 1
      DOCKER_USERNAME: mitmbot
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pip install tox
      - uses: actions/download-artifact@v2
        with:
          name: wheel
          path: release/dist
      - run: tox -e cibuild -- build
      - run: tox -e cibuild -- upload

  deploy:
    if: github.repository == 'recipopdev/mitmproxy' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [test, test-web-ui, build-wheel, build-binaries]
    env:
      CI_BUILD_WHEEL: 1
      CI_BUILD_PYINSTALLER: 1
      CI_BUILD_WININSTALLER: 1
      TWINE_USERNAME: mitmproxy
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/download-artifact@v2
        with:
          path: release/dist
      # move artifacts from their subfolders into release/dist
      - run: find release/dist -mindepth 2 -type f -exec mv {} release/dist \;
      # and then delete the empty folders
      - run: find release/dist -type d -empty -delete
      - run: ls release/dist
      - run: pip install tox
      - run: tox -e cibuild -- upload
